#TODO update to bcc-repos 
resolver: https://raw.githubusercontent.com/The-Blockchain-Company/bcc-prelude/316c854d1d3089f480708ad5cd5ecf8a74423ddd/snapshot.yaml

packages:
- ./bcc-shell
- ./bcc-launcher

extra-deps:
  - katip-0.8.3.0
  - quickcheck-state-machine-0.6.0  # Used a specific dependency, new release.
  - pretty-show-1.9.5               # Used for quickcheck-state-machine.
  - time-units-1.0.0
  - silently-1.2.5.1
  - network-3.1.1.1

  - Win32-2.5.4.1@sha256:e623a1058bd8134ec14d62759f76cac52eee3576711cb2c4981f398f1ec44b85

  - git: https://github.com/The-Blockchain-Company/bcc-prelude
    commit: 316c854d1d3089f480708ad5cd5ecf8a74423ddd
    subdirs:
      - .
      - test

  - git: https://github.com/The-Blockchain-Company/bcc-monitoring-framework
    commit: efa4b5ecd7f0a13124616b12679cd42517cd905a
    subdirs:
      - contra-tracer
      - tbco-monitoring
      - tracer-transformers
#TODO add network repo
  - git: https://github.com/The-Blockchain-Company/shardagnostic-network
    commit: 1361bb92814c65e5964732777fc7f8ec9ebdccfe
    subdirs:
      - Win32-network

  # Extracted from bcc-sl since it's quite useful
  #TODOupdate commit number
  - git: https://github.com/The-Blockchain-Company/bcc-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49
    subdirs:
      - .

nix:
  shell-file: stack-shell.nix
