#TODO Klarity, x509, aws
walletLogging: false
nodeArgs:
- --tlsca
- ${XDG_DATA_HOME}/Klarity/staging/tls/server/ca.crt
- --tlscert
- ${XDG_DATA_HOME}/Klarity/staging/tls/server/server.crt
- --tlskey
- ${XDG_DATA_HOME}/Klarity/staging/tls/server/server.key
- --no-client-auth
- --log-console-off
- --update-server
- https://update-awstest.tbcodev.io
- --keyfile
- ${XDG_DATA_HOME}/Klarity/staging/Secrets/secret.key
- --topology
- ${BccWallet_CONFIG}/wallet-topology.yaml
- --wallet-db-path
- ${XDG_DATA_HOME}/Klarity/staging/Wallet
- --update-latest-path
- ${XDG_DATA_HOME}/Klarity/staging/installer.sh
- --wallet-address
- 127.0.0.1:0
- --update-with-package
- --metrics
- --ekg-server
- localhost:8082
- +RTS
- -T
- -RTS
statePath: ${XDG_DATA_HOME}/Klarity/staging
walletPath: Klarity-frontend
nodePath: bcc-node
launcherLogsPrefix: ${XDG_DATA_HOME}/Klarity/staging/Logs/
walletArgs: []
nodeDbPath: ${XDG_DATA_HOME}/Klarity/staging/DB/
updaterPath: /bin/update-runner
workingDir: ${XDG_DATA_HOME}/Klarity/staging
frontendOnlyMode: true
nodeLogPath: null
updaterArgs: []
logsPrefix: ${XDG_DATA_HOME}/Klarity/staging/Logs
configuration:
  seed: null
  filePath: ${BccWallet_CONFIG}/configuration.yaml
  key: mainnet_dryrun_wallet_linux64
  systemStart: null
updateArchive: ${XDG_DATA_HOME}/Klarity/staging/installer.sh
nodeLogConfig: ${BccWallet_CONFIG}/log-config-prod.yaml
nodeTimeoutSec: 60
tlsPath: ${XDG_DATA_HOME}/Klarity/staging/tls
x509ToolPath: bcc-x509-certificates
