#TODOBccWallet, x509tool path confirm
# This is configuration that is used to manually test the launcher
walletLogging: false
nodeArgs:
- --tlsca
- ${XDG_DATA_HOME}/Klarity/mainnet/tls/server/ca.crt
- --tlscert
- ${XDG_DATA_HOME}/Klarity/mainnet/tls/server/server.crt
- --tlskey
- ${XDG_DATA_HOME}/Klarity/mainnet/tls/server/server.key
- --no-client-auth
- --log-console-off
- --update-server
- https://update-bcc-mainnet.The-Blockchain-Company.io
- --keyfile
- ${XDG_DATA_HOME}/Klarity/mainnet/Secrets/secret.key
- --topology
- ${BccWallet_CONFIG}/wallet-topology.yaml
- --wallet-db-path
- ${XDG_DATA_HOME}/Klarity/mainnet/Wallet
- --update-latest-path
- ${XDG_DATA_HOME}/Klarity/mainnet/installer.sh
- --wallet-address
- 127.0.0.1:0
- --update-with-package
statePath: .
walletPath: ./bcc-launcher/test/testBccWalletFrontend.sh
nodePath: bcc-node
launcherLogsPrefix: ${XDG_DATA_HOME}/Klarity/mainnet/Logs/
walletArgs: []
nodeDbPath: ${XDG_DATA_HOME}/Klarity/mainnet/DB/
updaterPath: bash
workingDir: ./
frontendOnlyMode: true
nodeLogPath: null
updaterArgs: ["main"]
logsPrefix: ${XDG_DATA_HOME}/Klarity/mainnet/Logs
configuration:
  seed: null
  filePath: ./bcc-launcher/configuration/cert-configuration.yaml
  key: dev
  systemStart: null
updateArchive: ./bcc-launcher/test/testUpdater.sh
nodeLogConfig: ${BccWallet_CONFIG}/log-config-prod.yaml
nodeTimeoutSec: 60
tlsPath: "./configuration"
x509ToolPath: bcc-x509-certificates
